// Sample data for testing and development
export const categories = [
  { id: "1", name: "Pulpen & Pensil", description: "Alat tulis dasar" },
  { id: "2", name: "Spidol & Marker", description: "Alat tulis warna" },
  { id: "3", name: "Buku & Notes", description: "Media tulis" },
  { id: "4", name: "Map & Folder", description: "Penyimpanan dokumen" },
  { id: "5", name: "Kertas & Amplop", description: "Media cetak" },
  { id: "6", name: "Perlengkapan Kantor", description: "Alat kantor lainnya" },
]

export const sampleProducts = [
  {
    id: "1",
    name: "Pulpen Pilot G2",
    description: "Pulpen gel dengan tinta halus dan nyaman digunakan",
    category: "Pulpen & Pensil",
    brand: "Pilot",
    price: 15000,
    stock: 50,
    image_url: "",
    sku: "PLT-G2-001",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Spidol Snowman",
    description: "Spidol permanen dengan berbagai warna",
    category: "Spidol & Marker",
    brand: "Snowman",
    price: 25000,
    stock: 30,
    image_url: "",
    sku: "SNW-SPD-001",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Buku Tulis Campus",
    description: "Buku tulis 58 lembar dengan kualitas kertas terbaik",
    category: "Buku & Notes",
    brand: "Campus",
    price: 8000,
    stock: 100,
    image_url: "",
    sku: "CMP-BT-001",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Map Plastik A4",
    description: "Map plastik transparan ukuran A4",
    category: "Map & Folder",
    brand: "Generic",
    price: 5000,
    stock: 75,
    image_url: "",
    sku: "GEN-MAP-001",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Kertas HVS A4",
    description: "Kertas HVS putih 80gsm isi 500 lembar",
    category: "Kertas & Amplop",
    brand: "PaperOne",
    price: 45000,
    stock: 20,
    image_url: "",
    sku: "P1-HVS-001",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Stapler Kenko",
    description: "Stapler heavy duty untuk penggunaan kantor",
    category: "Perlengkapan Kantor",
    brand: "Kenko",
    price: 35000,
    stock: 15,
    image_url: "",
    sku: "KNK-STP-001",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const getCategoryIcon = (categoryName: string) => {
  const iconMap: Record<string, string> = {
    "Pulpen & Pensil": "✏️",
    "Spidol & Marker": "🖊️",
    "Buku & Notes": "📓",
    "Map & Folder": "📁",
    "Kertas & Amplop": "📄",
    "Perlengkapan Kantor": "📎",
  }
  return iconMap[categoryName] || "📦"
}
